// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaVwNEfyGqyuISr9aS80EUMADsMbHJYmc',
    appId: '1:1038181647217:web:88ba69fc678adaebd8acd0',
    messagingSenderId: '1038181647217',
    projectId: 'transmalogi',
    authDomain: 'transmalogi.firebaseapp.com',
    storageBucket: 'transmalogi.appspot.com',
    measurementId: 'G-40NDS4XJEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlSo5SgRAstaWpyaJYuznIBLgIE-fzW_o',
    appId: '1:1038181647217:android:f545fcf7f2fc837dd8acd0',
    messagingSenderId: '1038181647217',
    projectId: 'transmalogi',
    storageBucket: 'transmalogi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUs661gA1_NTyaJZXg4iAGtSfvsC1Atc0',
    appId: '1:1038181647217:ios:3bdd4a2f6678dbbdd8acd0',
    messagingSenderId: '1038181647217',
    projectId: 'transmalogi',
    storageBucket: 'transmalogi.appspot.com',
    iosBundleId: 'com.example.logistics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUs661gA1_NTyaJZXg4iAGtSfvsC1Atc0',
    appId: '1:1038181647217:ios:aa181acee788bf34d8acd0',
    messagingSenderId: '1038181647217',
    projectId: 'transmalogi',
    storageBucket: 'transmalogi.appspot.com',
    iosBundleId: 'com.example.logistics.RunnerTests',
  );
}
